repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-added-large-files
        args: ["--maxkb=1024"]
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: name-tests-test
    -   id: check-json
    -   id: check-toml
    -   id: check-xml
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: debug-statements
    -   id: pretty-format-json
        args: ["--autofix", "--indent=4", "--no-sort-keys"]

-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
    -   id: remove-tabs

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.3
    hooks:
    -   id: ruff-check
    -   id: ruff-format
