[build-system]
requires = [
  "setuptools",
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 80
target-version = ['py39']
include = '\.pyi?$'

[tool.isort]
profile = "black"

[tool.pyright]
pythonVersion = '3.9'
venvPath = ''
venv = ''